const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 650,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, these golden-brown delights are perfect when stacked high and drizzled with maple syrup`,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 1300,
      img: './images/item-2.jpeg',
      desc: `Indulge in a classic diner experience with our double-stack of fluffy buttermilk pancakes, a timeless breakfast favorite`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 600,
      img: './images/item-3.jpeg',
      desc: `Experience the monstrous deliciousness of our Godzilla milkshake, an epic blend of rich chocolate, towering whipped cream, and a cascade of delectable toppings that will leave your taste buds roaring for more`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 2000,
      img: './images/item-4.jpeg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 2200,
      img: './images/item-5.jpeg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 1800,
      img: './images/item-6.jpeg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 800,
      img: './images/item-7.jpeg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 1200,
      img: './images/item-8.jpeg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Nyama Choma',
      category: 'Main Course',
      price: 1800,
      img: './images/item-9.jpeg',
      desc: `Tender grilled meat, a Kenyan specialty, served with flavorful spices and sides.`,
    },
    {
      id: 10,
      title: 'Ugali and Sukuma Wiki',
      category: 'Main Course',
      price: 1200,
      img: './images/item-10.jpeg',
      desc: `A staple Kenyan dish with maize porridge (ugali) and collard greens (sukuma wiki).`,
    },
    {
      id: 11,
      title: 'Mandazi',
      category: 'Snack',
      price: 350,
      img: './images/item-11.jpeg',
      desc: `Sweet, deep-fried dough delights, perfect for a quick snack.`,
    },
    {
      id: 12,
      title: 'Chai Tea',
      category: 'Beverage',
      price: 450,
      img: './images/item-12.jpeg',
      desc: `A warm and comforting cup of Kenyan spiced tea.`,
    },
  
    
  ];
  export default menu;